### PR TITLE
Update Forestry configuration

### PR DESCRIPTION
**Pull request by SangamSwadiK**
#### Type of contribution
- [x] Code
- [ ] Documentation

#### Reference: Issue or Pull Request (PR)
- [x] Towards #12    [this will keep reference issue or PR open]  <=== _When in doubt, pick this one._
- [ ] Fixes #xxx. See also #xxx   [this will close the referenced issue or PR]
- [ ] Resolves #xxx, #xxx [for multiple issues, this will close them]

## Description: What does this implement/fix? Explain your changes.
Updates the configuration for forestry which enables preview

#### Reminders

- [x] Did you review the [CONTRIBUTING GUIDE](https://github.com/data-umbrella/data-umbrella-website/blob/main/CONTRIBUTING.md)?
- [x] Did you reference an issue or another pull request?

### CODE REVIEW

**Comment by reshamas** [comment]
> @reshamas Hi, would it be possible for you to try this out ? On a separate branch? Once you are logged in, you have to click on `add site` and provide the repository name along with branch, and then go to the settings>previews and click on start preview.

@SangamSwadiK 
Are there instructions for using Forestry?
For example, do we need to create an account? Clone the repo?

**Comment by reshamas** [comment]
I tested Forestry with Sangam.

Does @symeneses want to test it next?

**Comment by symeneses** [comment]
> I tested Forestry with Sangam.
> 
> Does @symeneses want to test it next?

It's possible to add collaborators to a project or leave it open? So that people we want to contribute don't have to setup the site. Could I try it with the configuration you have done already?

**Comment by reshamas** [comment]
> > I tested Forestry with Sangam.
> > Does @symeneses want to test it next?
> 
> It's possible to add collaborators to a project or leave it open? So that people we want to contribute don't have to setup the site. Could I try it with the configuration you have done already?

@SangamSwadiK What are your thoughts on this?

**Comment by reshamas** [comment]
Sounds good @SangamSwadiK.
We should probably focus first on adding the content, then doing the bells and whistles (images, etc) anyway.

**Pull request closed without merging**
